schema_version = "1.0.0"

id = "pseudo_rendering_farm_ex"
version = "1.1.1-ex"
name = "Pseudo Rendering Farm EX"
tagline = "Spawns multiple background processes to render the current file (extended fork)"
maintainer = "Maxim Kuprikov"
type = "add-on"

website = "https://github.com/maximkuprikov/PseudoRenderingFarm"
tags = ["Render"]

blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
# Required for os.remove and tempfile (cleaning up corrupted frames and benchmarking)
files = "Required to manage output files and temporary benchmark data"

[build]
# excludes files/folders in builds run by Blender (`blender.exe --command extension build`).
paths = [
  "__init__.py",
]
