name: Check formatting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-zip:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: PseudoRenderingFarm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Black
        run: pip install black
      - name: Run Black Check
        run: black --check .
      - name: Install Blender
        run: sudo snap install blender --classic
      - name: Build Blender Extension
        run: blender --command extension build
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ./*.zip
          archive: false
          if-no-files-found: error
          retention-days: 5
