name: Test and pack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-pack:
    runs-on: macos-latest
    env:
      PROJECT_NAME: PseudoRenderingFarm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Black
        run: pip install black
      - name: Run Black Check
        run: black --check .
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install Blender
        run: brew install blender
      - name: Build Blender Extension
        run: blender --command extension build
      - name: Install dependencies
        run: pip install pytest psutil
      - name: Run Pytest
        working-directory: ./tests
        run: pytest -s test.py -x
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ./*.zip
          archive: false
          if-no-files-found: error
          retention-days: 5
